### ISSUE TITLE
width of buffer at the left is not showing the full length of the pull request number

### ISSUE THREAD

**Issue by etheleon** [rhysd/ghpr-blame.vim#8]
Hi, when I use `:GHPRBlame` it brings up the pull request IDs on the left, but the width of the buffer is always too narrow.

![screen shot 2018-06-27 at 11 14 55 am](https://user-images.githubusercontent.com/2868858/41950998-64453d82-79fb-11e8-86e4-9571fda877ea.png)

**Comment by rhysd** [comment]
Thank you for reporting this. I found that line number was not considered (I usually don't display line numbers). I addressed this at d8bad9d. Please try the latest.
